global:
  edition: ce

  hosts:
    domain: gitlab.local.com
    https: false

  ingress:
    class: azure-application-gateway
    configureCertmanager: false

  psql:
    host: gitlab-postgres.postgres.database.azure.com
    port: 5432
    username: gitlabadmin
    database: gitlabhq_production
    password:
      secret: gitlab-postgres-secret
      key: password

  redis:
    host: gitlab-redis-aks-001.redis.cache.windows.net
    port: 6380
    scheme: rediss

    auth:
      enabled: true
      secret: gitlab-redis-secret
      key: password

  appConfig:
    object_store:
      enabled: true
      connection:
        provider: AzureRM
        azure_storage_account_name: gitlabstorage
        azure_storage_access_key:
          secret: gitlab-storage-secret
          key: key

certmanager-issuer:
  enabled: false
  email: admin@gitlab.local.com

postgresql:
  install: false

redis:
  install: false

nginx-ingress:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

gitlab-runner:
  enabled: false

registry:
  enabled: false

minio:
  enabled: false

gitlab:
  webservice:
    ingress:
      enabled: true

  kas:
    enabled: false