global:
  edition: ce

  hosts:
    domain: nip.io
    https: false

  ingress:
    class: azure-application-gateway
    configureCertmanager: false

  minio:
    enabled: false

  psql:
    host: gitlab-postgres.postgres.database.azure.com
    port: 5432
    username: gitlabadmin
    database: gitlabhq_production
    password:
      secret: gitlab-postgres-secret
      key: password

  redis:
    host: gitlab-redis-aks-001.redis.cache.windows.net
    port: 6380
    scheme: rediss

    auth:
      enabled: true

    password:
      secret: gitlab-redis-secret
      key: password

  appConfig:
    object_store:
      enabled: false

postgresql:
  install: false

redis:
  install: false

nginx-ingress:
  enabled: false

prometheus:
  install: false

grafana:
  enabled: false

gitlab-runner:
  install: false

registry:
  enabled: false

certmanager:
  install: false

gitlab:
  kas:
    enabled: false