global:
  edition: ce

  hosts:
    domain: nip.io
    https: false

  ingress:
    class: azure-application-gateway
    configureCertmanager: false

  minio:
    enabled: false

  psql:
    host: gitlab-postgres.postgres.database.azure.com
    port: 5432
    username: gitlabadmin
    database: gitlabhq_production
    password:
      secret: gitlab-postgres-secret
      key: password

  redis:
    host: gitlab-redis-aks.redis.cache.windows.net
    port: 6380
    scheme: rediss

    auth:
      enabled: true

    password:
      secret: gitlab-redis-secret
      key: password

  appConfig:
    object_store:
      enabled: true

      connection:
        secret: gitlab-storage-secret
        key: connection

postgresql:
  install: false

redis:
  install: false

nginx-ingress:
  enabled: false

certmanager:
  installCRDs: false

prometheus:
  install: false

grafana:
  enabled: false

registry:
  enabled: false

gitlab-runner:
  install: false

gitlab-exporter:
  enabled: false

gitlab:
  kas:
    enabled: false

  sidekiq:
    replicas: 1

  gitlab-shell:
    replicas: 1

  toolbox:
    replicas: 1

    backups:
      objectStorage:
        backend: azureRM

  webservice:
    minReplicas: 1
    maxReplicas: 1

    ingress:
      enabled: false